server:
  port: 9898
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9191/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
      
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    singlesignon:
      addHeader: 
      path: /singlesignon/**
      serviceId: singlesignon      
      filters: AddRequestHeader=Authorization, Basic Y2xpZW50SWRQYXNzd29yZDpzZWNyZXQ=
      stripPrefix: false                